
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: cms_device_app_development

  
test:
  <<: *default
  database: cms_device_app_test


production:
  <<: *default
  database: cms_device_app_production
  username: cms_device_app
  password: <%= ENV['CMS_DEVICE_APP_DATABASE_PASSWORD'] %>
